package Chain_of_Responsibility;

import org.junit.Test;

/**
 * Created by dylanb on 16/03/2018.
 */
public class NumbersTest {
    @Test
    public void getNumber1() throws Exception {
    }

    @Test
    public void getNumber2() throws Exception {
    }

    @Test
    public void getCalculationnWanted() throws Exception {
    }

}